/*
 * This source file was generated by the Gradle 'init' task
 */
package org.seedfilter;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.entity.BlockEntity;
import net.minecraft.server.MinecraftServer;
import net.minecraft.util.math.BlockPos;

public class SeedFilter {
    public static void main(String[] args) {
        System.out.println("Started ");
    }
}
